/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and degradation
         * @description Always 200.
         *
         *     A degraded API is still a working API: contracts and vocabulary resolve
         *     without a database. Returning 500 here would make an ordinary cold start
         *     look like an outage.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is the observatory actually observing? */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Semantic vocabulary */
        get: operations["vocabulary_api_vocabulary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global conditions */
        get: operations["weather_api_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The Trends page, in one call
         * @description Bounded by design: four ranked bands plus recent events.
         *
         *     A single request so the page paints at once — assembling one screen from four
         *     round trips is what makes an interface feel like a dashboard.
         */
        get: operations["trends_api_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technologies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Technology universe */
        get: operations["technologies_api_technologies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technologies/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research page header */
        get: operations["technology_api_technologies__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technologies/{slug}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal history */
        get: operations["technology_history_api_technologies__slug__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technologies/{slug}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Related technologies */
        get: operations["technology_relationships_api_technologies__slug__relationships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detected ecosystem events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event with evidence */
        get: operations["event_api_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue an investigation
         * @description Returns immediately with a job. The frontend never blocks on research.
         */
        post: operations["create_api_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/{research_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll an investigation */
        get: operations["read_api_research__research_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/{research_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the Research Copilot
         * @description Contextual to one research topic, grounded in Internet Weather data.
         *
         *     Not a general-purpose chatbot: an answer it cannot ground in stored evidence
         *     is an answer it must decline to give.
         */
        post: operations["chat_api_research__research_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatReply
         * @description A Copilot answer. Grounded in Internet Weather data or it does not ship.
         */
        ChatReply: {
            /** Reply */
            reply: string;
            epistemic_status: components["schemas"]["EpistemicStatus"];
            /** Evidence */
            evidence?: components["schemas"]["EvidenceLink"][];
            /** Data Used */
            data_used?: string[];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
        };
        /**
         * DataFreshness
         * @description How current, and how trustworthy, the numbers behind a response are.
         *
         *     Present on every data response. A platform that claims to observe the
         *     internet has to be explicit about when it last actually looked.
         */
        DataFreshness: {
            /**
             * As Of
             * @description ISO date of the latest computed signal day.
             */
            as_of?: string | null;
            /**
             * Observed Days
             * @description Distinct days of observation backing these signals.
             * @default 0
             */
            observed_days: number;
            /**
             * Has Data
             * @default false
             */
            has_data: boolean;
            /**
             * Degraded Reason
             * @description Why data is missing, when it is. Null when has_data is true.
             */
            degraded_reason?: string | null;
        };
        /** DatabaseHealth */
        DatabaseHealth: {
            /** Configured */
            configured: boolean;
            /** Reachable */
            reachable: boolean;
            /** Error */
            error?: string | null;
        };
        /**
         * EpistemicStatus
         * @description Required label on every generated claim.
         *
         *     Enforced at the contract level so speculation can never be presented as
         *     fact. See CLAUDE.md, "LLM Philosophy".
         * @enum {string}
         */
        EpistemicStatus: "observation" | "inference" | "hypothesis" | "unknown";
        /** EventDetail */
        EventDetail: {
            /** Id */
            id: number;
            event_type: components["schemas"]["EventType"];
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /** Magnitude */
            magnitude: number;
            /** Confidence */
            confidence: number;
            epistemic_status: components["schemas"]["EpistemicStatus"];
            /** Technology Slug */
            technology_slug?: string | null;
            /** Technology Name */
            technology_name?: string | null;
            /** Repository Full Name */
            repository_full_name?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** Detected At */
            detected_at?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceLink"][];
        };
        /** EventList */
        EventList: {
            /** Items */
            items: components["schemas"]["EventSummary"][];
            page: components["schemas"]["Page"];
            freshness: components["schemas"]["DataFreshness"];
        };
        /** EventSummary */
        EventSummary: {
            /** Id */
            id: number;
            event_type: components["schemas"]["EventType"];
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /** Magnitude */
            magnitude: number;
            /** Confidence */
            confidence: number;
            epistemic_status: components["schemas"]["EpistemicStatus"];
            /** Technology Slug */
            technology_slug?: string | null;
            /** Technology Name */
            technology_name?: string | null;
            /** Repository Full Name */
            repository_full_name?: string | null;
        };
        /**
         * EventType
         * @description Discrete ecosystem events.
         * @enum {string}
         */
        EventType: "release" | "star_spike" | "anomaly" | "new_repository" | "archived" | "renamed";
        /**
         * EvidenceLink
         * @description A traceable source for a claim.
         *
         *     Present on every event so "show me the evidence" is answerable without a
         *     round trip through the research engine.
         */
        EvidenceLink: {
            /** Label */
            label: string;
            /** Url */
            url?: string | null;
            /**
             * Detail
             * @description The measured value that triggered this, when applicable.
             */
            detail?: string | null;
        };
        /**
         * Finding
         * @description One claim, with its epistemic standing attached.
         *
         *     ``epistemic_status`` is required, not optional. That is the mechanism by
         *     which speculation cannot be presented as fact.
         */
        Finding: {
            /** Statement */
            statement: string;
            epistemic_status: components["schemas"]["EpistemicStatus"];
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceLink"][];
            /** Counter Evidence */
            counter_evidence?: components["schemas"]["EvidenceLink"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness plus honest degradation.
         *
         *     ``status`` is ``ok`` when data can be served and ``degraded`` when the API is
         *     up but has no database. Degraded is a real product state, not a failure: the
         *     contracts and vocabulary still resolve.
         */
        Health: {
            /**
             * Status
             * @description ok | degraded
             */
            status: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            database: components["schemas"]["DatabaseHealth"];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
        };
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            weather_state: components["schemas"]["WeatherState"];
            /** Momentum */
            momentum: number;
            /** Confidence */
            confidence: number;
            /** Stars Total */
            stars_total: number;
            /** Stars Delta 1D */
            stars_delta_1d?: number | null;
            /** Star Velocity 7D */
            star_velocity_7d?: number | null;
            /** Activity Score */
            activity_score?: number | null;
        };
        /**
         * IngestionSummary
         * @description Last run per job. How you know whether the observatory is actually looking.
         */
        IngestionSummary: {
            /** Source */
            source: string;
            /** Job */
            job: string;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Api Calls
             * @default 0
             */
            api_calls: number;
            /**
             * Api Calls Saved
             * @default 0
             */
            api_calls_saved: number;
            /**
             * Records Written
             * @default 0
             */
            records_written: number;
            /** Rate Limit Remaining */
            rate_limit_remaining?: number | null;
            /** Error */
            error?: string | null;
        };
        /** Page */
        Page: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** RelatedTechnology */
        RelatedTechnology: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            subdomain: components["schemas"]["Subdomain"];
            weather_state?: components["schemas"]["WeatherState"] | null;
            relation_type: components["schemas"]["RelationshipType"];
            /** Strength */
            strength: number;
            epistemic_status: components["schemas"]["EpistemicStatus"];
        };
        /**
         * RelationshipType
         * @description Edges between technologies, used by Explore and the Research page.
         * @enum {string}
         */
        RelationshipType: "depends_on" | "alternative_to" | "complements" | "co_occurs";
        /**
         * RepoRelation
         * @description How a repository relates to the technology it sensors.
         * @enum {string}
         */
        RepoRelation: "canonical" | "implementation" | "integration" | "ecosystem";
        /**
         * RepositorySensor
         * @description A repository observed on behalf of a technology.
         */
        RepositorySensor: {
            /** Full Name */
            full_name: string;
            relation: components["schemas"]["RepoRelation"];
            /** Weight */
            weight: number;
            /** Stars */
            stars: number;
            /** Forks */
            forks: number;
            /** Primary Language */
            primary_language?: string | null;
            /**
             * Is Archived
             * @default false
             */
            is_archived: boolean;
            /** Pushed At */
            pushed_at?: string | null;
            /** Url */
            url: string;
        };
        /** ResearchJob */
        ResearchJob: {
            /** Research Id */
            research_id: string;
            status: components["schemas"]["ResearchStatus"];
            /** Technology Slug */
            technology_slug?: string | null;
            /** Question */
            question?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Progress Note */
            progress_note?: string | null;
        };
        /** ResearchRequest */
        ResearchRequest: {
            /** Technology Slug */
            technology_slug?: string | null;
            /** Event Id */
            event_id?: number | null;
            /**
             * Question
             * @description Optional focus, e.g. 'Why is MCP accelerating?'
             */
            question?: string | null;
        };
        /** ResearchResult */
        ResearchResult: {
            /** Research Id */
            research_id: string;
            status: components["schemas"]["ResearchStatus"];
            /** Technology Slug */
            technology_slug?: string | null;
            /** Question */
            question?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Progress Note */
            progress_note?: string | null;
            executive_finding?: components["schemas"]["Finding"] | null;
            /** Supporting Findings */
            supporting_findings?: components["schemas"]["Finding"][];
            /**
             * Unknowns
             * @description What the evidence could not settle.
             */
            unknowns?: string[];
            /** Watch Next */
            watch_next?: string[];
        };
        /**
         * ResearchStatus
         * @enum {string}
         */
        ResearchStatus: "queued" | "collecting" | "analyzing" | "synthesizing" | "completed" | "failed";
        /**
         * SignalSnapshot
         * @description The measured numbers behind a weather state.
         *
         *     Every field here is an OBSERVATION or a deterministic transform of one. The
         *     UI may show these without an epistemic caveat.
         */
        SignalSnapshot: {
            /**
             * Momentum
             * @description Normalised -1..1 composite. Positive = accelerating.
             */
            momentum: number;
            /** Confidence */
            confidence: number;
            /** Stars Total */
            stars_total: number;
            /** Stars Delta 7D */
            stars_delta_7d?: number | null;
            /** Stars Delta 28D */
            stars_delta_28d?: number | null;
            /**
             * Star Velocity 7D
             * @description Weighted stars/day over the trailing 7 days.
             */
            star_velocity_7d?: number | null;
            /**
             * Star Acceleration
             * @description Change in velocity — what 'heating up' actually means.
             */
            star_acceleration?: number | null;
            /** Activity Score */
            activity_score?: number | null;
            /** Commit Velocity 7D */
            commit_velocity_7d?: number | null;
            /** Release Count 28D */
            release_count_28d?: number | null;
            /** Contributor Count 28D */
            contributor_count_28d?: number | null;
            /**
             * Anomaly Z
             * @description Standard deviations from this technology's own baseline.
             */
            anomaly_z?: number | null;
            /**
             * Repo Count
             * @default 0
             */
            repo_count: number;
            /**
             * Active Repo Count
             * @default 0
             */
            active_repo_count: number;
            /**
             * Sample Days
             * @description Observed days backing this row. Low values mean low confidence.
             * @default 0
             */
            sample_days: number;
        };
        /**
         * Subdomain
         * @description Technology subdomains within the AI-engineering domain.
         * @enum {string}
         */
        Subdomain: "agentic_ai" | "llm_ecosystem" | "rag" | "ai_infra" | "multimodal" | "mlops" | "ai_security";
        /**
         * SubdomainClimate
         * @description Aggregate weather for one subdomain — the radar's regional readout.
         */
        SubdomainClimate: {
            subdomain: components["schemas"]["Subdomain"];
            /** Label */
            label: string;
            /** Technology Count */
            technology_count: number;
            /** Mean Momentum */
            mean_momentum: number;
            dominant_state: components["schemas"]["WeatherState"];
            /** State Counts */
            state_counts?: {
                [key: string]: number;
            };
        };
        /** SubdomainInfo */
        SubdomainInfo: {
            key: components["schemas"]["Subdomain"];
            /** Label */
            label: string;
        };
        /** SystemStatus */
        SystemStatus: {
            health: components["schemas"]["Health"];
            /** Ingestion */
            ingestion?: components["schemas"]["IngestionSummary"][];
            /**
             * Tracked Technologies
             * @default 0
             */
            tracked_technologies: number;
            /**
             * Tracked Repositories
             * @default 0
             */
            tracked_repositories: number;
            /**
             * Observed Days
             * @default 0
             */
            observed_days: number;
        };
        /**
         * TechnologyCard
         * @description One technology as it appears on Trends, including its hover preview.
         *
         *     Deliberately self-sufficient: the hover intelligence preview must not fire a
         *     second request, so the sparkline and explanation ship with the card.
         */
        TechnologyCard: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            subdomain: components["schemas"]["Subdomain"];
            /** Summary */
            summary?: string | null;
            /**
             * Headline
             * @default false
             */
            headline: boolean;
            weather_state: components["schemas"]["WeatherState"];
            signals: components["schemas"]["SignalSnapshot"];
            /** Spark */
            spark?: number[];
            /** Explanation */
            explanation?: string | null;
            /** @default observation */
            epistemic_status: components["schemas"]["EpistemicStatus"];
            /** Rank Overall */
            rank_overall?: number | null;
            /** Rank Subdomain */
            rank_subdomain?: number | null;
            /** As Of */
            as_of?: string | null;
        };
        /**
         * TechnologyDetail
         * @description The Research page header: what we know, and what it rests on.
         */
        TechnologyDetail: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            subdomain: components["schemas"]["Subdomain"];
            /** Summary */
            summary?: string | null;
            /** Aliases */
            aliases?: string[];
            /**
             * Headline
             * @default false
             */
            headline: boolean;
            /** First Seen At */
            first_seen_at?: string | null;
            weather_state?: components["schemas"]["WeatherState"] | null;
            signals?: components["schemas"]["SignalSnapshot"] | null;
            /** Explanation */
            explanation?: string | null;
            /** @default observation */
            epistemic_status: components["schemas"]["EpistemicStatus"];
            /** Repositories */
            repositories?: components["schemas"]["RepositorySensor"][];
            freshness: components["schemas"]["DataFreshness"];
        };
        /** TechnologyHistory */
        TechnologyHistory: {
            /** Slug */
            slug: string;
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
            freshness: components["schemas"]["DataFreshness"];
        };
        /** TechnologyList */
        TechnologyList: {
            /** Items */
            items: components["schemas"]["TechnologyCard"][];
            page: components["schemas"]["Page"];
            freshness: components["schemas"]["DataFreshness"];
        };
        /** TechnologyRelationships */
        TechnologyRelationships: {
            /** Slug */
            slug: string;
            /** Related */
            related: components["schemas"]["RelatedTechnology"][];
            freshness: components["schemas"]["DataFreshness"];
        };
        /**
         * Trends
         * @description Everything the Trends page renders.
         */
        Trends: {
            /** As Of */
            as_of?: string | null;
            overview: components["schemas"]["WeatherOverview"];
            /** Heating */
            heating?: components["schemas"]["TechnologyCard"][];
            /** Cooling */
            cooling?: components["schemas"]["TechnologyCard"][];
            /** Emerging */
            emerging?: components["schemas"]["TechnologyCard"][];
            /** Anomalies */
            anomalies?: components["schemas"]["TechnologyCard"][];
            /** Events */
            events?: components["schemas"]["EventSummary"][];
            freshness: components["schemas"]["DataFreshness"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Vocabulary
         * @description Everything the UI needs to label data it did not compute.
         */
        Vocabulary: {
            /** Weather States */
            weather_states: components["schemas"]["WeatherStateInfo"][];
            /** Subdomains */
            subdomains: components["schemas"]["SubdomainInfo"][];
            /** Epistemic Statuses */
            epistemic_statuses: components["schemas"]["EpistemicStatus"][];
        };
        /**
         * WeatherOverview
         * @description Global conditions. The one-glance answer.
         */
        WeatherOverview: {
            /** As Of */
            as_of?: string | null;
            /**
             * Technology Count
             * @default 0
             */
            technology_count: number;
            /** State Counts */
            state_counts?: {
                [key: string]: number;
            };
            /**
             * Mean Momentum
             * @default 0
             */
            mean_momentum: number;
            /** Subdomains */
            subdomains?: components["schemas"]["SubdomainClimate"][];
            freshness: components["schemas"]["DataFreshness"];
        };
        /**
         * WeatherState
         * @description Computed atmospheric state of a technology.
         *
         *     NEVER assign these by hand. They are the output of
         *     ``internetweather.analysis.weather_state.classify`` operating on measured
         *     signals. A technology with insufficient history is STABLE with low
         *     confidence — not EMERGING.
         * @enum {string}
         */
        WeatherState: "hot" | "emerging" | "stable" | "cooling" | "breaking" | "storm";
        /**
         * WeatherStateInfo
         * @description Presentation metadata for one weather state.
         *
         *     Served so the frontend renders the semantic vocabulary from the API instead
         *     of hardcoding glyphs that could drift from the classifier.
         */
        WeatherStateInfo: {
            state: components["schemas"]["WeatherState"];
            /** Glyph */
            glyph: string;
            /** Label */
            label: string;
            /** Meaning */
            meaning: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    vocabulary_api_vocabulary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vocabulary"];
                };
            };
        };
    };
    weather_api_weather_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherOverview"];
                };
            };
        };
    };
    trends_api_trends_get: {
        parameters: {
            query?: {
                subdomain?: components["schemas"]["Subdomain"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trends"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    technologies_api_technologies_get: {
        parameters: {
            query?: {
                subdomain?: components["schemas"]["Subdomain"] | null;
                state?: components["schemas"]["WeatherState"][] | null;
                order?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnologyList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    technology_api_technologies__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnologyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    technology_history_api_technologies__slug__history_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnologyHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    technology_relationships_api_technologies__slug__relationships_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnologyRelationships"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                subdomain?: components["schemas"]["Subdomain"] | null;
                technology?: string | null;
                event_type?: components["schemas"]["EventType"][] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_api_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The research engine is not implemented in this slice. The contract is final; the implementation follows the first vertical slice. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_api_research__research_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The research engine is not implemented in this slice. The contract is final; the implementation follows the first vertical slice. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_api_research__research_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatReply"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The research engine is not implemented in this slice. The contract is final; the implementation follows the first vertical slice. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
